### ISSUE TITLE
Installing the package depends on requests and semver

### ISSUE THREAD

**Issue by dmartinalbo** [configcat/python-sdk#12]
Hi, guys!

Installing configcat-client via pip seems to depend on requests and semver packages. 

This is problematic in general, in particular when using Docker, because you would tend to do something like the following:
`pip3 --disable-pip-version-check --no-cache-dir install requests semver configcat-client`

The problem seems to come from importing configcatclient file in `setup.py`. This triggers the import of `__init__.py` that triggers ... until reaching a file that imports the requests package.

In addition, although in the documentation here in GitHub it is correct. In the documentation of ConfigCat Console it appears the following code snippet:
`newjoke = configcat_client.get_value('newjoke', false)`

The F of false should be uppercased.

**Comment by baltuonis** [comment]
Same problem

**Comment by dmas-at-wiris** [comment]
I saw the issue has being solved. Thanks! 

Closing

**Comment by dmartinalbo** [comment]
I saw the issue has being solved. Thanks!
