### ISSUE TITLE
Client expects the cache to be persistent

### ISSUE THREAD

**Issue by davidmoss** [configcat/python-sdk#14]
All the Policies (Auto, Lazy and Manual) require the cache to be persistent. If `self._config_cache.get()` is ever None for any external invalidation reason then because the `self._config_fetcher` has an `etag` set it never fetches and re-sets the cache. Instead you just get a warning that it's empty and the default_value.

Can you etag be invalidated if the cache is empty so the config is always available?

**Comment by kp-cat** [comment]
Thanks for reporting this issue, we will look into this problem and get back to you.

**Comment by davidmoss** [comment]
Fixed with https://github.com/configcat/python-sdk/pull/16
