### ISSUE TITLE
Exceptions in AutoPollingCachePolicy can crash the thread

### ISSUE THREAD

**Issue by ejholmes** [configcat/python-sdk#4]
We saw an issue earlier where toggling feature flags was having no effect. I started digging, and found this in logs:

```console
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/site-packages/configcatclient/autopollingcachepolicy.py", line 54, in run
  File "/usr/local/lib/python2.7/site-packages/configcatclient/autopollingcachepolicy.py", line 83, in force_refresh
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exception'
```

What happens is:

1. An exception is raised within `AutoPollingCachePolicy` during a fetch (e.g. a timeout opening a connection)
2. The exception is caught in https://github.com/configcat/python-sdk/blob/dc3f9f4bdb0b4e5ab149106d30cc5cad9ed5ced8/configcatclient/autopollingcachepolicy.py#L83
3. Somehow, `log` is None so `log.exception()` raises `<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exception'`, which crashes the thread.
4. The thread is dead, so any changes to feature flags take no effect.

I have no idea how `log` could be None in this context, but it seemingly can happen (it could also be related to the environment we're running in, which is django + uWSGI).

If the thread was supervised, this would be less of an issue, as it could recover by spawning a new thread.

**Comment by configcat** [comment]
Hi ejholmes,

Thanks for trying ConfigCat and opening an issue. We created a `django + uWSGI + ConfigCat` project but couldn't reproduce the issue.
Could you please send us a sample project with which we could reproduce the problem?

**Comment by ejholmes** [comment]
@configcat thanks for the response. I believe this ended up being specific to our django configuration (although I can't recall what the issue was off hand). Anyways, not an issue for us any more! Closing.

**Comment by configcat** [comment]
Sounds good! Have fun using ConfigCat!
